pipeline{
  agent any

  stages{
    stage('Setup Selenium Grid') {
      steps {

        sh 'mvn test -Dtest=YourTestClass -Dbrowser=chrome -DhubUrl=http://your-grid-url:4444/wd/hub'
        // Wait for Selenium Grid to initialize
        sleep 20
      }
    }
    stage('install playwright'){
      steps{
          bat 'npm i -D @playwright/test'
          bat 'npx playwright install'

      }
    }
    stage('help'){
      steps{
        bat 'npx playwright test --help'
      }
    }
    stage('test'){
      steps{
          bat 'npx playwright test --list'
          bat 'npx playwright test'
          bat 'mvn test'

      }
    }
  }
  post {
    always {
      // Clean up the workspace
      cleanWs()
    }
  }
}